import { validateCreativeProject } from '../src/creative/validation.js';
import type { CreativeProject } from '../src/creative/types.js';

console.log('=== VERIFYING REPRESENTATIVE CREATIVE JSON V2 SAMPLES ===\n');

// 1. High-Energy Creator Hook
const sample1_creatorHook: CreativeProject = {
  version: 1,
  id: 'proj_sample_creator_hook',
  name: 'Stop Scrolling If You Want More Views',
  fps: 30,
  durationInFrames: 360,
  input: {
    mode: 'idea',
    text: 'A high energy viral hook about short form retention hacks.',
    sourceLanguage: 'en',
    outputLanguage: 'en',
  },
  creativeIntent: {
    contentType: 'marketing',
    tone: 'punchy',
    energy: 'high',
    pacing: 'fast',
    visualStyle: 'viral_bold',
  },
  globalSettings: {
    typography: {
      presetName: 'Viral Hook',
      fontSizeMultiplier: 1.0,
      textColor: '#FFFFFF',
      textTransform: 'uppercase',
      position: 'center',
      textAlign: 'center',
      keywordHighlightEnabled: true,
      highlightColor: '#0066FF',
      highlightIntensity: 0.7,
    },
    animation: 'signature',
    effects: {
      filmGrainEnabled: true,
      filmGrainIntensity: 'low',
      gradientOverlayEnabled: true,
      gradientOverlayDirection: 'bottom',
      gradientOverlayOpacity: 0.6,
      gradientOverlayStrength: 0.5,
      gradientOverlayColor: '#000000',
      filmDustEnabled: false,
      halationEnabled: false,
      halationIntensity: 'medium',
      gridEnabled: false,
      gridIntensity: 'medium',
      crtScanlinesEnabled: false,
      crtScanlinesIntensity: 'medium',
      halftoneEnabled: false,
      halftoneIntensity: 'medium',
      lightLeakEnabled: false,
      lightLeakIntensity: 'medium',
      chromaticAberrationEnabled: false,
      chromaticAberrationIntensity: 'medium',
      audioPulseEnabled: false,
      audioPulseIntensity: 'medium',
      keywordPunchEnabled: false,
      keywordPunchIntensity: 'medium',
    },
    composition: {
      layout: 'full-bleed',
      variant: 'none',
      bgColor: '#000000',
      bezelRadiusMultiplier: 1,
    },
    overlay: {
      progressBarEnabled: true,
      progressBarColor: '#0066FF',
      progressBarPosition: 'bottom',
      watermarkEnabled: false,
      watermarkPosition: 'bottom-right',
      watermarkOpacity: 70,
    },
    motion: {
      codeBlockEnabled: false,
      codeBlockCode: '',
      codeBlockLanguage: 'js',
      codeBlockPosition: 'center',
      codeBlockLinesPerPage: 10,
      numberCounterEnabled: false,
      numberCounterStart: 0,
      numberCounterEnd: 100,
      numberCounterPrefix: '',
      numberCounterSuffix: '%',
      tickerEnabled: false,
      tickerText: '',
      tickerDirection: 'left',
      tickerPosition: 'bottom',
    },
    videoMotion: {
      type: 'static',
    },
  },
  beats: [
    {
      id: 'beat_01',
      type: 'hook',
      startFrame: 0,
      endFrame: 90,
      content: {
        text: 'Stop scrolling if you want to double your retention.',
        words: [
          { text: 'Stop', startMs: 0, endMs: 400 },
          { text: ' scrolling', startMs: 400, endMs: 1000 },
          { text: ' if', startMs: 1000, endMs: 1300 },
          { text: ' you', startMs: 1300, endMs: 1600 },
          { text: ' want', startMs: 1600, endMs: 1900 },
          { text: ' to', startMs: 1900, endMs: 2100 },
          { text: ' double', startMs: 2100, endMs: 2500 },
          { text: ' your', startMs: 2500, endMs: 2700 },
          { text: ' retention.', startMs: 2700, endMs: 3000 },
        ],
      },
      visual: {
        typography: {
          fontSizeMultiplier: 1.3,
          keywords: ['Stop', 'double', 'retention'],
        },
        animation: 'splitReveal',
        videoMotion: { type: 'zoom-in', intensity: 'medium' },
        effects: {
          keywordPunchEnabled: true,
          keywordPunchIntensity: 'high',
        },
      },
      transition: {
        assetId: 'flash',
        startFrame: 0,
        durationInFrames: 8,
        opacity: 0.9,
      },
      sfx: {
        assetId: 'impact',
        startFrame: 0,
        volume: 0.85,
      },
    },
    {
      id: 'beat_02',
      type: 'core_point',
      startFrame: 90,
      endFrame: 210,
      content: {
        text: 'The secret is visual pacing in the first three seconds.',
      },
      visual: {
        typography: {
          keywords: ['visual pacing', 'three seconds'],
          highlightColor: '#FBBF24',
        },
        animation: 'signature',
        videoMotion: { type: 'ken-burns', intensity: 'subtle' },
      },
      sfx: {
        assetId: 'pop_bubble',
        startFrame: 90,
        volume: 0.5,
      },
    },
    {
      id: 'beat_03',
      type: 'call_to_action',
      startFrame: 210,
      endFrame: 360,
      content: {
        text: 'Save this video and test it on your next upload.',
      },
      visual: {
        typography: {
          fontSizeMultiplier: 1.15,
          keywords: ['Save this video', 'next upload'],
        },
        animation: 'slideUp',
      },
      sfx: {
        assetId: 'notification',
        startFrame: 210,
        volume: 0.7,
      },
    },
  ],
  assets: {
    transitions: ['flash'],
    sfx: ['impact', 'pop_bubble', 'notification'],
  },
};

// 2. Educational Explanation
const sample2_educational: CreativeProject = {
  version: 1,
  id: 'proj_sample_educational',
  name: 'How Photosynthesis Converts Light',
  fps: 30,
  durationInFrames: 450,
  input: {
    mode: 'idea',
    text: 'A clean scientific breakdown of plant chlorophyll.',
    sourceLanguage: 'en',
    outputLanguage: 'en',
  },
  creativeIntent: {
    contentType: 'educational',
    tone: 'authoritative',
    energy: 'medium',
    pacing: 'moderate',
    visualStyle: 'clean_modern',
  },
  globalSettings: {
    typography: {
      presetName: 'Soft Modern',
      fontSizeMultiplier: 1.0,
      textColor: '#FFFFFF',
      lineHeight: 1.3,
      position: 'center',
      textAlign: 'center',
      keywordHighlightEnabled: true,
      highlightColor: '#22C55E',
      highlightIntensity: 0.5,
    },
    animation: 'sentenceBlock',
    effects: {
      filmGrainEnabled: false,
      filmGrainIntensity: 'low',
      gradientOverlayEnabled: true,
      gradientOverlayDirection: 'bottom',
      gradientOverlayOpacity: 0.55,
      gradientOverlayStrength: 0.5,
      gradientOverlayColor: '#000000',
      filmDustEnabled: false,
      halationEnabled: false,
      halationIntensity: 'medium',
      gridEnabled: false,
      gridIntensity: 'medium',
      crtScanlinesEnabled: false,
      crtScanlinesIntensity: 'medium',
      halftoneEnabled: false,
      halftoneIntensity: 'medium',
      lightLeakEnabled: false,
      lightLeakIntensity: 'medium',
      chromaticAberrationEnabled: false,
      chromaticAberrationIntensity: 'medium',
      audioPulseEnabled: false,
      audioPulseIntensity: 'medium',
      keywordPunchEnabled: false,
      keywordPunchIntensity: 'medium',
    },
    composition: {
      layout: 'full-bleed',
      variant: 'none',
      bgColor: '#000000',
      bezelRadiusMultiplier: 1,
    },
    overlay: {
      progressBarEnabled: true,
      progressBarColor: '#22C55E',
      progressBarPosition: 'top',
      watermarkEnabled: false,
      watermarkPosition: 'bottom-right',
      watermarkOpacity: 70,
    },
    motion: {
      codeBlockEnabled: false,
      codeBlockCode: '',
      codeBlockLanguage: 'js',
      codeBlockPosition: 'center',
      codeBlockLinesPerPage: 10,
      numberCounterEnabled: false,
      numberCounterStart: 0,
      numberCounterEnd: 100,
      numberCounterPrefix: '',
      numberCounterSuffix: '%',
      tickerEnabled: false,
      tickerText: '',
      tickerDirection: 'left',
      tickerPosition: 'bottom',
    },
    videoMotion: {
      type: 'ken-burns',
    },
  },
  beats: [
    {
      id: 'beat_01',
      type: 'hook',
      startFrame: 0,
      endFrame: 120,
      content: { text: 'Plants absorb sunlight and water to manufacture glucose.' },
      visual: {
        typography: { keywords: ['sunlight', 'water', 'glucose'] },
        animation: 'calmPhrase',
      },
      sfx: { assetId: 'pop_soft', startFrame: 0, volume: 0.4 },
    },
    {
      id: 'beat_02',
      type: 'explanation',
      startFrame: 120,
      endFrame: 270,
      content: { text: 'Inside chloroplasts, chlorophyll traps photon energy.' },
      visual: {
        typography: { keywords: ['chloroplasts', 'chlorophyll', 'photon energy'] },
        animation: 'sentenceBlock',
      },
    },
    {
      id: 'beat_03',
      type: 'conclusion',
      startFrame: 270,
      endFrame: 450,
      content: { text: 'The byproduct is the clean oxygen we breathe every day.' },
      visual: {
        typography: { fontSizeMultiplier: 1.15, keywords: ['oxygen'] },
        animation: 'calmPhrase',
      },
      sfx: { assetId: 'whoosh_simple', startFrame: 270, volume: 0.5 },
    },
  ],
  assets: {
    transitions: [],
    sfx: ['pop_soft', 'whoosh_simple'],
  },
};

// 3. Technical / Developer Content
const sample3_technical: CreativeProject = {
  version: 1,
  id: 'proj_sample_technical',
  name: 'How Async Await Really Works',
  fps: 30,
  durationInFrames: 390,
  input: {
    mode: 'idea',
    text: 'A developer walkthrough explaining the JS event loop.',
    sourceLanguage: 'en',
    outputLanguage: 'en',
  },
  creativeIntent: {
    contentType: 'educational',
    tone: 'authoritative',
    energy: 'medium',
    pacing: 'fast',
    visualStyle: 'retro_tech',
  },
  globalSettings: {
    typography: {
      presetName: 'Cinematic',
      fontSizeMultiplier: 1.0,
      textColor: '#F8FAFC',
      letterSpacing: 0.5,
      position: 'bottom',
      textAlign: 'center',
    },
    animation: 'typewriter',
    effects: {
      gridEnabled: true,
      gridIntensity: 'low',
      crtScanlinesEnabled: true,
      crtScanlinesIntensity: 'low',
      filmGrainEnabled: false,
      filmGrainIntensity: 'low',
      gradientOverlayEnabled: false,
      gradientOverlayDirection: 'bottom',
      gradientOverlayOpacity: 0.6,
      gradientOverlayStrength: 0.5,
      gradientOverlayColor: '#000000',
      filmDustEnabled: false,
      halationEnabled: false,
      halationIntensity: 'medium',
      halftoneEnabled: false,
      halftoneIntensity: 'medium',
      lightLeakEnabled: false,
      lightLeakIntensity: 'medium',
      chromaticAberrationEnabled: false,
      chromaticAberrationIntensity: 'medium',
      audioPulseEnabled: false,
      audioPulseIntensity: 'medium',
      keywordPunchEnabled: false,
      keywordPunchIntensity: 'medium',
    },
    composition: {
      layout: 'floating-card',
      variant: 'terminal',
      bgColor: '#0A0A0C',
      bezelRadiusMultiplier: 1,
      cardMode: 'custom',
      customScale: 0.88,
      customAspectRatio: '9:16',
      customBorderRadius: 20,
      customBackdrop: 'gradient',
      customBackdropGradient: 'linear-gradient(180deg, #09090b 0%, #1e1b4b 50%, #0284c7 100%)',
    },
    overlay: {
      progressBarEnabled: true,
      progressBarColor: '#00D4FF',
      progressBarPosition: 'top',
      watermarkEnabled: false,
      watermarkPosition: 'bottom-right',
      watermarkOpacity: 70,
    },
    motion: {
      codeBlockEnabled: true,
      codeBlockCode: 'const res = await fetch(url);\nconst data = await res.json();',
      codeBlockLanguage: 'js',
      codeBlockPosition: 'top',
      codeBlockLinesPerPage: 4,
      numberCounterEnabled: false,
      numberCounterStart: 0,
      numberCounterEnd: 100,
      numberCounterPrefix: '',
      numberCounterSuffix: '%',
      tickerEnabled: false,
      tickerText: '',
      tickerDirection: 'left',
      tickerPosition: 'bottom',
    },
    videoMotion: {
      type: 'static',
    },
  },
  beats: [
    {
      id: 'beat_01',
      type: 'hook',
      startFrame: 0,
      endFrame: 120,
      content: { text: 'Stop blocking your Node thread with synchronous loops.' },
      visual: {
        typography: { keywords: ['blocking', 'Node thread'] },
        effects: { chromaticAberrationEnabled: true, chromaticAberrationIntensity: 'medium' },
      },
      sfx: { assetId: 'click_mouse', startFrame: 0, volume: 0.6 },
    },
    {
      id: 'beat_02',
      type: 'core_point',
      startFrame: 120,
      endFrame: 260,
      content: { text: 'Use non-blocking microtask queues to handle concurrency.' },
      visual: {
        typography: { keywords: ['microtask queues', 'concurrency'] },
      },
      sfx: { assetId: 'typing', startFrame: 120, volume: 0.7 },
    },
    {
      id: 'beat_03',
      type: 'payoff',
      startFrame: 260,
      endFrame: 390,
      content: { text: 'Your throughput scales instantly across every CPU core.' },
      visual: {
        typography: { fontSizeMultiplier: 1.25, keywords: ['throughput', 'every CPU core'] },
      },
      sfx: { assetId: 'glitch_transition', startFrame: 260, volume: 0.7 },
    },
  ],
  assets: {
    transitions: [],
    sfx: ['click_mouse', 'typing', 'glitch_transition'],
  },
};

// 4. Storytelling / Personal Narrative (Cinematic Reveal with camera_flash)
const sample4_narrative: CreativeProject = {
  version: 1,
  id: 'proj_sample_narrative',
  name: 'The Moment Everything Changed',
  fps: 30,
  durationInFrames: 420,
  input: {
    mode: 'idea',
    text: 'A dramatic personal turning point.',
    sourceLanguage: 'en',
    outputLanguage: 'en',
  },
  creativeIntent: {
    contentType: 'storytelling',
    tone: 'dramatic',
    energy: 'medium',
    pacing: 'deliberate',
    visualStyle: 'cinematic_dark',
  },
  globalSettings: {
    typography: {
      presetName: 'Editorial',
      fontSizeMultiplier: 1.0,
      textColor: '#F1F5F9',
      position: 'bottom',
      textAlign: 'center',
    },
    animation: 'calmPhrase',
    effects: {
      filmGrainEnabled: true,
      filmGrainIntensity: 'medium',
      halationEnabled: true,
      halationIntensity: 'low',
      lightLeakEnabled: true,
      lightLeakIntensity: 'low',
      gradientOverlayEnabled: true,
      gradientOverlayDirection: 'bottom',
      gradientOverlayOpacity: 0.7,
      gradientOverlayStrength: 0.6,
      gradientOverlayColor: '#000000',
      filmDustEnabled: false,
      gridEnabled: false,
      gridIntensity: 'medium',
      crtScanlinesEnabled: false,
      crtScanlinesIntensity: 'medium',
      halftoneEnabled: false,
      halftoneIntensity: 'medium',
      chromaticAberrationEnabled: false,
      chromaticAberrationIntensity: 'medium',
      audioPulseEnabled: false,
      audioPulseIntensity: 'medium',
      keywordPunchEnabled: false,
      keywordPunchIntensity: 'medium',
    },
    composition: {
      layout: 'full-bleed',
      variant: 'cinematicScope',
      bgColor: '#000000',
      bezelRadiusMultiplier: 1,
    },
    overlay: {
      progressBarEnabled: false,
      progressBarColor: '#0066FF',
      progressBarPosition: 'bottom',
      watermarkEnabled: false,
      watermarkPosition: 'bottom-right',
      watermarkOpacity: 70,
    },
    motion: {
      codeBlockEnabled: false,
      codeBlockCode: '',
      codeBlockLanguage: 'js',
      codeBlockPosition: 'center',
      codeBlockLinesPerPage: 10,
      numberCounterEnabled: false,
      numberCounterStart: 0,
      numberCounterEnd: 100,
      numberCounterPrefix: '',
      numberCounterSuffix: '%',
      tickerEnabled: false,
      tickerText: '',
      tickerDirection: 'left',
      tickerPosition: 'bottom',
    },
    videoMotion: {
      type: 'ken-burns',
      speed: 'slow',
    },
  },
  beats: [
    {
      id: 'beat_01',
      type: 'setup',
      startFrame: 0,
      endFrame: 140,
      content: { text: 'For three years, I worked in complete obscurity.' },
      visual: {
        typography: { keywords: ['three years', 'obscurity'] },
      },
    },
    {
      id: 'beat_02',
      type: 'reveal',
      startFrame: 140,
      endFrame: 280,
      content: { text: 'Then overnight, the camera flash changed our entire life.' },
      visual: {
        typography: {
          fontSizeMultiplier: 1.25,
          keywords: ['overnight', 'camera flash'],
        },
        animation: 'blurResolve',
        videoMotion: { type: 'zoom-in', intensity: 'medium' },
      },
      transition: {
        assetId: 'flash',
        startFrame: 140,
        durationInFrames: 10,
        opacity: 0.85,
      },
      sfx: {
        assetId: 'camera_flash',
        startFrame: 140,
        volume: 0.8,
      },
    },
    {
      id: 'beat_03',
      type: 'conclusion',
      startFrame: 280,
      endFrame: 420,
      content: { text: 'Consistency is the only bridge between dreams and reality.' },
      visual: {
        typography: {
          keywords: ['Consistency', 'reality'],
        },
      },
      sfx: {
        assetId: 'impact_cinematic',
        startFrame: 280,
        volume: 0.6,
      },
    },
  ],
  assets: {
    transitions: ['flash'],
    sfx: ['camera_flash', 'impact_cinematic'],
  },
};

// 5. Statistics / Results-Driven Content (with Number Counter and Keyword Punch)
const sample5_statistics: CreativeProject = {
  version: 1,
  id: 'proj_sample_statistics',
  name: '94 Percent Of Startups Fail',
  fps: 30,
  durationInFrames: 360,
  input: {
    mode: 'idea',
    text: 'A hard statistical breakdown of founder failure rates.',
    sourceLanguage: 'en',
    outputLanguage: 'en',
  },
  creativeIntent: {
    contentType: 'educational',
    tone: 'punchy',
    energy: 'high',
    pacing: 'fast',
    visualStyle: 'modern_bold',
  },
  globalSettings: {
    typography: {
      presetName: 'Heavy Display',
      fontSizeMultiplier: 1.0,
      textColor: '#FFFFFF',
      textTransform: 'uppercase',
      letterSpacing: -1.0,
      position: 'center',
      textAlign: 'center',
      keywordHighlightEnabled: true,
      highlightColor: '#FBBF24',
      highlightIntensity: 0.8,
    },
    animation: 'signature',
    effects: {
      filmGrainEnabled: true,
      filmGrainIntensity: 'low',
      gradientOverlayEnabled: true,
      gradientOverlayDirection: 'bottom',
      gradientOverlayOpacity: 0.65,
      gradientOverlayStrength: 0.6,
      gradientOverlayColor: '#000000',
      filmDustEnabled: false,
      halationEnabled: false,
      halationIntensity: 'medium',
      gridEnabled: false,
      gridIntensity: 'medium',
      crtScanlinesEnabled: false,
      crtScanlinesIntensity: 'medium',
      halftoneEnabled: false,
      halftoneIntensity: 'medium',
      lightLeakEnabled: false,
      lightLeakIntensity: 'medium',
      chromaticAberrationEnabled: false,
      chromaticAberrationIntensity: 'medium',
      audioPulseEnabled: false,
      audioPulseIntensity: 'medium',
      keywordPunchEnabled: false,
      keywordPunchIntensity: 'medium',
    },
    composition: {
      layout: 'full-bleed',
      variant: 'none',
      bgColor: '#000000',
      bezelRadiusMultiplier: 1,
    },
    overlay: {
      progressBarEnabled: true,
      progressBarColor: '#FBBF24',
      progressBarPosition: 'bottom',
      watermarkEnabled: false,
      watermarkPosition: 'bottom-right',
      watermarkOpacity: 70,
    },
    motion: {
      codeBlockEnabled: false,
      codeBlockCode: '',
      codeBlockLanguage: 'js',
      codeBlockPosition: 'center',
      codeBlockLinesPerPage: 10,
      numberCounterEnabled: true,
      numberCounterStart: 0,
      numberCounterEnd: 94,
      numberCounterPrefix: '',
      numberCounterSuffix: '%',
      tickerEnabled: false,
      tickerText: '',
      tickerDirection: 'left',
      tickerPosition: 'bottom',
    },
    videoMotion: {
      type: 'static',
    },
  },
  beats: [
    {
      id: 'beat_01',
      type: 'statistic',
      startFrame: 0,
      endFrame: 120,
      content: { text: '94% of all startups die within their first 36 months.' },
      visual: {
        typography: {
          fontSizeMultiplier: 1.4,
          keywords: ['94%', '36 months'],
        },
        animation: 'wordStamp',
        videoMotion: { type: 'zoom-in', intensity: 'heavy' },
        effects: {
          keywordPunchEnabled: true,
          keywordPunchIntensity: 'high',
        },
      },
      sfx: { assetId: 'bass_hit_punchy', startFrame: 0, volume: 0.9 },
    },
    {
      id: 'beat_02',
      type: 'explanation',
      startFrame: 120,
      endFrame: 240,
      content: { text: 'The fatal mistake is running out of cash before finding product market fit.' },
      visual: {
        typography: {
          keywords: ['cash', 'product market fit'],
          highlightColor: '#EF4444',
        },
      },
      sfx: { assetId: 'riser_sharp_short', startFrame: 120, volume: 0.6 },
    },
    {
      id: 'beat_03',
      type: 'payoff',
      startFrame: 240,
      endFrame: 360,
      content: { text: 'Protect your runway and validate demand on day one.' },
      visual: {
        typography: {
          fontSizeMultiplier: 1.2,
          keywords: ['runway', 'day one'],
        },
        animation: 'splitReveal',
      },
      sfx: { assetId: 'impact', startFrame: 240, volume: 0.75 },
    },
  ],
  assets: {
    transitions: [],
    sfx: ['bass_hit_punchy', 'riser_sharp_short', 'impact'],
  },
};

const samples = [
  { name: '1. High-Energy Creator Hook', doc: sample1_creatorHook },
  { name: '2. Clean Educational Story', doc: sample2_educational },
  { name: '3. Technical / Developer Walkthrough', doc: sample3_technical },
  { name: '4. Cinematic Narrative Reveal (with camera_flash)', doc: sample4_narrative },
  { name: '5. Statistics / Results-Driven (with counter & punch)', doc: sample5_statistics },
];

let pass = 0;
for (const s of samples) {
  const res = validateCreativeProject(s.doc);
  if (!res.isValid) {
    console.error(`[FAIL] ${s.name}: ${res.errors.map((e) => `${e.path}: ${e.message}`).join(', ')}`);
  } else {
    console.log(`[PASS] ${s.name}`);
    pass++;
  }
}

console.log(`\n==================================================`);
console.log(`SAMPLE GENERATION RESULTS: ${pass} / ${samples.length} valid`);
console.log(`==================================================\n`);

if (pass !== samples.length) {
  process.exit(1);
}
